### ISSUE TITLE
Arrow keys to increment / decrement values don't work

### ISSUE THREAD

**Issue by ova2** [jkuri/ngTouchSpin#1]
With the native jQuery plugin you can increment / decrement values by using arrow keys up / down. It doesn't work yet with the Angular version.

**Comment by jkuri** [comment]
No, not yet, but I plan to implement that in the future. If you are in hurry, pull requests are welcome.

**Comment by ova2** [comment]
I'm not in hurry, but maybe I can provide a pull request.

**Comment by giolvani** [comment]
I did a pull request https://github.com/jkuri/ngTouchSpin/pull/3

I hope to help you.

**Comment by jkuri** [comment]
Sorry for late response.. working now, check out my last commit.
