### ISSUE TITLE
You can't set initial value after angular render 

### ISSUE THREAD

**Issue by scamjayi** [jkuri/ngTouchSpin#5]
I need to edit data and set the initial value in the touchSpin control, after retrive the data doing an asyncronic call to the server.

For example: This works fine:
```javascript
vm.prize.points = 19;
<input type="text" value="{{vm.prize.points}}" ng-model="vm.prize.points" prefix="Pts" ng-touch-spin>
```
This does't work:
I get the vm.prize.points from DB using a service. (after angular render the expressions)

```javascript
    function getPrize(prizeId) {
        prizeService.show({ prizeId: prizeId })
             .$promise.then(onShowPrize, onError);
    }

    function onShowPrize(response) {
        vm.prize = response.data;
        vm.prize.points = 10;
    }

<input type="text" value="{{vm.prize.points}}" ng-model="vm.prize.points" prefix="Pts" ng-touch-spin>
```
The ng-touch-sping is empty

What can i do? any ideas?
Thank you!

**Comment by nicosuarez** [comment]
I have the same problem. It would be great if you could fix it.

**Comment by jkuri** [comment]
Hi,

I fixed this using ngModel.$render. Tested and working now. Sorry for late response.
